### ISSUE TITLE
BUG: Fix touch event

### ISSUE THREAD

**Issue by co0p** [as-ideas/mediahackday-ideas#2]
Currently the upload button does not really work on touch event. This reduces the amount of traffic and lowers the fun to use the app. please fix it

**Comment by TiTaTomte** [comment]
Quote from https://material.angularjs.org/latest/getting-started:

ngTouch - ngMaterial conflicts with ngTouch for click, tap, and swipe support on touch-enabled devices.

So this could be the reason...

**Comment by co0p** [comment]
Well, we are not using ng-touch. So there should not be a conflict.

**Comment by co0p** [comment]
unless otherwise noted; touch event now works as expected. See https://github.com/as-ideas/mediahackday-ideas/pull/6
